### ISSUE TITLE
Getting NYC and Kansas output file names

### ISSUE THREAD

**Issue by bhagwat26** [jiabowang/GAPIT#197]
I AM GETTING  TWO RESULTS FOR A TRAIT WITH DIFFERENCES.

![Image](https://github.com/user-attachments/assets/abd44198-549a-452f-8a8b-71d3c6159f1c)

![Image](https://github.com/user-attachments/assets/46420dc6-9a93-421c-8248-ec79b667ffb5)

all files have name like this GAPIT.Association.Manhattan_Geno.MLM.Sim(NYC).pdf

Script terminating with this error.>>[1] "Reading GWAS result with MLM.Sim"
Error in file(file, "rt") : cannot open the connection
In addition: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by jiabowang** [comment]
Hi, we are adding some new functions. Now I have fixed that error. Please try again.

**Comment by bhagwat26** [comment]
Thanks..now working!!!!

**Comment by sivasubramanics** [comment]
Again, it's the same issue. Probably make a dev branch for adding NYC and Kansas stuff. And keep a clean gapit_functions.txt with the release version. 

Even the source provided in the homepage. has this issue.
http://zzlab.net/GAPIT/gapit_functions.txt

-
Siva

**Comment by bhagwat26** [comment]
for me 
only working if removed..
Multiple_analysis=TRUE, 

Tried many ways to remove (NYC) and (Kansas) from file names, but did not work..
Until resolved, work without Multiple_analysis.

**Comment by jiabowang** [comment]
I have fixed this error and tested it works.
Please try with the newest version function:
source("https://raw.githubusercontent.com/jiabowang/GAPIT/refs/heads/master/gapit_functions.txt", encoding = "UTF-8")
If there is still error, please feel free contact me.

**Comment by RafaelGoncalvesMarmo** [comment]
Hi,
Thank you so much for your help; however, the problem continues today (6/2/25) using the new source. The output files still have Kansas and NYC on it. When I open the files the results seems reasonable and the correlation among the same collumns across files are 1. This may help you to identify the solution.

**Comment by jiabowang** [comment]
@RafaelGoncalvesMarmo I mean the error has been fixed. The 'Kansas' and 'NYC' results are different. The 'Kansas' is same as previous. The 'NYC' is a new result after more multiple iterations. The function will be introduced in GAPIT 4.

**Comment by MKPIARI** [comment]
The  same error of getting two result files named "kansas" and "NYC", still persists. Kindly, resolve the issue or let us know, which file is providing the reliable results, so that we can proceed further.

**Comment by MKPIARI** [comment]
][[
